export const SHADCN_COMPONENTS = [
  "accordion",
  "alert",
  "alert-dialog",
  "aspect-ratio",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "collapsible",
  "combobox",
  "command",
  "context-menu",
  "data-table",
  "date-picker",
  "dialog",
  "drawer",
  "dropdown-menu",
  "form",
  "hover-card",
  "input",
  "input-otp",
  "label",
  "menubar",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "separator",
  "sheet",
  "sidebar",
  "skeleton",
  "slider",
  "sonner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "toggle",
  "toggle-group",
  "tooltip",
];

export const EXCLUDED_FILES = [
  "registry.json",
  "project-registry.json",
  "shadcn-registry.config.json",
  "shadcn_registry_cli.js",
  "shadcn_registry_cli.ts",
  "next-env.d.ts",
];

export const EXCLUDED_EXTENSIONS = [
  ".md",
  ".mjs",
  ".json",
  ".d.ts",
  ".lock",
  ".yaml",
  ".yml",
  ".ico",
];

export const CONFIG_FILE_PATTERNS = [
  "eslint.config",
  "next.config",
  "postcss.config",
  "tailwind.config",
  "vite.config",
  "webpack.config",
  "rollup.config",
  "babel.config",
  "jest.config",
  "vitest.config",
  "components.json",
];

export const EXCLUDED_DEPENDENCIES = [
  "next",
  "react",
  "react-dom",
  "tailwind-merge",
  "tw-animate-css",
  "class-variance-authority",
  "clsx",
];

export const EXCLUDED_DEV_DEPENDENCIES = [
  "@eslint/eslintrc",
  "@tailwindcss/postcss",
  "@types/node",
  "@types/react",
  "@types/react-dom",
  "eslint",
  "eslint-config-next",
  "tailwindcss",
  "typescript",
];

export const COMPONENT_FOLDERS = [
  "features",
  "modules",
  "sections",
  "layouts",
  "widgets",
  "containers",
  "views",
  "pages",
  "screens",
  "templates",
];

export const LIB_FOLDERS = [
  "helpers",
  "utilities",
  "shared",
  "common",
  "core",
  "tools",
  "validators",
  "schemas",
  "middleware",
  "plugins",
];

export const CONFIG_FILES = [
  "package.json",
  "tsconfig.json",
  "next.config.ts",
  "next.config.js",
  "tailwind.config.ts",
  "tailwind.config.js",
  "components.json",
  "eslint.config.js",
  "eslint.config.mjs",
  "postcss.config.js",
  "postcss.config.mjs",
  "vite.config.ts",
  "webpack.config.js",
];
